### ISSUE TITLE
can´t build wheels to cvxopt

### ISSUE THREAD

**Issue by JMK9904** [catalpa-cl/inceptalytics#27]
Hi,
I tried to install inceptalytics and can´t get around the error that it failed to build wheels to cvxopt.
I am new to programming and a bit overwhelmed on what I could and should do. If it helps I have a file with the command output attached. 
Am I understanding correctly that everything should work via pip install? I have a feeling that I am missing something...

Thank you in advance!

[Command Output.txt](https://github.com/catalpa-cl/inceptalytics/files/12937957/Command.Output.txt)

**Comment by zesch** [comment]
Not sure what is the problem here, but I must admit I do not have a lot of experience with (what seems to me) a Windows related problem.
As a workaround you could try to clone the whole project and install the dependencies (as listed in pyproject.toml) manually.

Note that we are currently changing the dependency management in inceptalytics to use [poetry](https://python-poetry.org). That should make things easier to use (in the near future).

**Comment by simulacrum6** [comment]
> Am I understanding correctly that everything should work via pip install? I have a feeling that I am missing something...

You are correct, `pip install inceptalytics` should work.

It seems that you are using python version 3.11. Due to dependency constraints, inceptalytics currently only supports python [3.9](https://www.python.org/downloads/release/python-3910/) and [3.10](https://www.python.org/downloads/release/python-31011/).
You could try to install one of the linked versions and see if that helps.

If it does not, it might be an issue with other dependencies in your virtual environment.
I would recommend creating a dedicated environment that only includes inceptalytics and perform your analysis through the virtual environment if possible.

Let me know if that helps.

**Comment by JMK9904** [comment]
I am sorry for the late reply.

I´ve switched to Colab to be able to work with Inceptalytics for now. 

I´ve tried different Python versions as suggested as well as a separate environment unsuccessfully.  Also, I tried to compile CVXOPT manually which ended up not being successful too. I am pretty sure it is an issue with my operating system. 
In a month I´ll be back at my main system where it will hopefully work. At that point, I will consider reinstalling the OS on my laptop to see if that will change anything. 

Thank you for your suggestions!

**Comment by zesch** [comment]
Did you find the problem?
Closing the issue for now. Please re-open if it was a problem with inceptalytics.
